cakephp/elastic-search

- composer.json
- src/Type.php
Up version of Elastica to ~1.4 as dependency.
Now tests are green again.
> Update Type methods with current RepositoryInterface

- LICENSE.txt
- src/Query.php
- src/Type.php
- tests/TestCase/TypeTest.php
This adds very basic save/delete behavior. I've not implemented:
* Validation
* Application rules
* Events
I'll be adding events/validation as my next task.
> Basic save & delete

- src/FilterBuilder.php
- tests/TestCase/FilterBuilderTest.php
- tests/TestCase/QueryTest.php
> Test filters

- src/Type.php
- tests/TestCase/TypeTest.php
Add analogous events to Type for delete and save operations.
> Add events to delete and save

- src/Marshaller.php
- src/Type.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/TypeTest.php
- tests/init.php
Add validation support similar to the behavior/scope of features available in ORM\Table.
> Add validation support

- src/Type.php
- tests/TestCase/TypeTest.php
Thankfully elastica made this very simple to implement.
> Basic implementation of exists().

- src/Type.php
- tests/TestCase/TypeTest.php
Implement deleteAll() by using [delete by query](http://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html).
> Implement deleteAll

- src/Query.php
- tests/TestCase/QueryTest.php
* Tests and documentation for where()
* Implemented postFilter()
> Where and post filter

- src/TestSuite/TestFixture.php
- src/Type.php
- tests/TestCase/TypeTest.php
Add application & domain rules support for save & delete for the ElasticSearch ODM.
Fixes #22
> Add rules support

- README.md
- config/bootstrap.php
- src/Datasource/Connection.php
- src/ResultSet.php
- src/Type.php
- src/View/Form/DocumentContext.php
- tests/TestCase/TypeTest.php
- tests/TestCase/View/Form/DocumentContextTest.php
Add bootstrap hooks and DebugKit compatibility. I've also made this plugin work with PaginatorComponent once the pull request to update `RepositoryInterface` is merged.
After this, I think we can tag a dev preview release as the plugin is usable in simple CRUD scenarios.
> Bootstrap hooks and DebugKit Integration

- src/Query.php
Hi,
I was wondering if there is currently any way to add facets / aggregations to the query. Cant seem to find this in the Query class.
> Facet / Aggregation support

- src/FilterBuilder.php
Reverts cakephp/elastic-search#56
> Revert "Make and/or methods protected"

- src/Type.php
- src/View/Form/DocumentContext.php
> Remove unused variables

- src/Association/EmbedMany.php
- src/Association/EmbedOne.php
- src/Datasource/Connection.php
- src/Document.php
- src/FilterBuilder.php
- src/Marshaller.php
- src/Query.php
- src/ResultSet.php
- src/TestSuite/TestFixture.php
- src/Type.php
- src/TypeRegistry.php
- src/View/Form/DocumentContext.php
- tests/TestCase/DocumentTest.php
- tests/TestCase/EmbeddedDocumentTest.php
- tests/TestCase/FilterBuilderTest.php
- tests/TestCase/QueryTest.php
- tests/TestCase/ResultSetTest.php
- tests/TestCase/TypeRegistryTest.php
- tests/TestCase/TypeTest.php
Clean up some docblocks and remove unused "use" statement.
> Cleanup namespaces and docblocks

- src/Datasource/Connection.php
- src/Datasource/SchemaCollection.php
The tests were failing because the SchemaCollection object did not retrieve the mapping names.
> Make listTables() work.

- README.md
Linking to the docs will get more people using it and hopefully help with more contributors.
> Added link to the docs

- src/Type.php
I'm not sure if this will break the plugins compatibility with older versions of cake `< 3.1`
> Replaced the deprecated class with it's replacement

- config/bootstrap.php
Unfortunately my assumptions about this change were wrong, reverting
> Revert "Lower priority to allow Types to be loaded in Controller::initialize"

- src/Type.php
- tests/TestCase/TypeTest.php
This allows errors from firstOrFail to work properly.
Refs #76
> Implement table() on Type.

- src/Type.php
This makes it match ORM\Table more.
Refs #79
> Add initialize hook for Type.

- src/Datasource/Connection.php
- tests/TestCase/Datasource/ConnectionTest.php
> Fix log option not working in constructor

- src/Datasource/Connection.php
Like we have here: https://github.com/cakephp/cakephp/blob/25943f1a6a31734fac6901dae9654f26fe552d3c/src/Database/Connection.php#L691
> "debug" is no longer needed

- src/Type.php
- tests/TestCase/TypeTest.php
> Fix for meta character being sent in request body during save

- src/Datasource/Connection.php
Fixed: _logger is no longer unset as Elastica\Client constructor sets to \Psr\Log\NullLogger
Fixed: data logged where context is an Exception or something else
> Fixes to log method

- src/Datasource/Connection.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/TypeRegistryTest.php
- tests/TestCase/View/Form/DocumentContextTest.php
> Remove double blank lines

- .travis.yml
- composer.json
- config/bootstrap.php
- src/Association/EmbedMany.php
- src/Association/EmbedOne.php
- src/Association/Embedded.php
- src/Datasource/Connection.php
- src/Datasource/MappingSchema.php
- src/Datasource/SchemaCollection.php
- src/Document.php
- src/Marshaller.php
- src/Query.php
- src/QueryBuilder.php
- src/ResultSet.php
- src/TestSuite/TestFixture.php
- src/Type.php
- src/TypeRegistry.php
- src/View/Form/DocumentContext.php
- tests/TestCase/Datasource/ConnectionTest.php
- tests/TestCase/DocumentTest.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/QueryTest.php
- tests/TestCase/ResultSetTest.php
- tests/TestCase/TypeRegistryTest.php
- tests/TestCase/TypeTest.php
- tests/TestCase/View/Form/DocumentContextTest.php
This marks the last feature I wanted for this branch of the repo. Once this is merged in, I will moved the code to the master branch and start working on a branch that will have elastic 5.x as a requirement, as it is good difficult to support the 2 major versions at the same time.
> Added support for should queries

- src/Type.php
- tests/TestCase/TypeTest.php
@lorenzo as discussed here is the method from the trait we use in our plugin.
> Adding saveMany()

- .travis.yml
- composer.json
- tests/init.php
This should get the builds running on all supported PHP versions.
> Update phpunit version constraint.

- src/QueryBuilder.php
#161 match() exists two times in this classe, guess this was caused by a merge.
> #161 Fixes a fatal error

- src/TestSuite/TestFixture.php
* Check if the connection name contains 'test'
* Add init function conform cake core
* Use TableRegistry to fetch the index name and type !
> Fixture improvements

- src/TestSuite/TestFixture.php
Follow up from previous PR (#178) that fixes some oversights.
On a side note: We should ad some unit tests for the fixture class in the future.
> Also use getName/getType from index on other fixture methods

- src/Index.php
> Fix RuntimeException use

- src/Index.php
- src/Plugin.php
- src/Query.php
- src/QueryBuilder.php
- src/ResultSet.php
> Fix some Annotations and fix an import on Plugin.php

- docs/en/4-0-upgrade-guide.rst
- docs/en/contents.rst
- src/Datasource/Log/ElasticLogger.php
- src/Index.php
- src/Marshaller.php
- src/ResultSet.php
- tests/TestCase/Datasource/ConnectionTest.php
- tests/TestCase/IndexTest.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/ResultSetTest.php
- tests/init.php
These changes got tests passing locally for me against elasticsearch 6.8
> 4.x - Get tests passing

- .coveralls.yml
- .travis.yml
- composer.json
- phpcs.xml.dist
- phpunit.xml.dist
- src/Association/EmbedMany.php
- src/Association/EmbedOne.php
- src/Association/Embedded.php
- src/Datasource/Connection.php
- src/Datasource/Log/ElasticLogger.php
- src/Document.php
- src/Index.php
- src/Marshaller.php
- src/Plugin.php
- src/Query.php
- src/QueryBuilder.php
- src/TestSuite/TestFixture.php
- src/View/Form/DocumentContext.php
- tests/TestCase/Datasource/ConnectionTest.php
- tests/TestCase/DocumentTest.php
- tests/TestCase/EmbeddedDocumentTest.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/QueryBuilderTest.php
- tests/TestCase/QueryTest.php
- tests/TestCase/ResultSetTest.php
Added code coverage. Fixed CS errors.
> Upated travis builds

- src/QueryBuilder.php
Closes https://github.com/cakephp/elastic-search/issues/224
> Add QueryBuilder::and() and or() and deprecate and_() and or_()

- composer.json
- phpcs.xml.dist
- src/Association/Embedded.php
- src/Datasource/Connection.php
- src/Datasource/Log/ElasticLogger.php
- src/Document.php
- src/Index.php
- src/Marshaller.php
- src/Query.php
- src/QueryBuilder.php
- src/ResultSet.php
- tests/Fixture/ArticlesFixture.php
- tests/Fixture/ProfilesFixture.php
- tests/TestCase/Datasource/ConnectionTest.php
- tests/TestCase/Datasource/MappingSchemaTest.php
- tests/TestCase/EmbeddedDocumentTest.php
- tests/TestCase/IndexTest.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/QueryBuilderTest.php
- tests/TestCase/QueryTest.php
- tests/TestCase/ResultSetTest.php
- tests/TestCase/RulesCheckerTest.php
- tests/TestCase/View/Form/DocumentContextTest.php
- tests/init.php
Copied phpcs config from 3.0 and auto-fixed all errors.
> 2.x - Updated CS

- README.md
- docs/en/index.rst
- docs/pt/index.rst
- src/Association/EmbedMany.php
- src/Association/EmbedOne.php
- src/Association/Embedded.php
- src/Index.php
- src/Marshaller.php
- src/MissingDocumentException.php
- src/ResultSet.php
- src/View/Form/DocumentContext.php
- tests/TestCase/EmbeddedDocumentTest.php
- tests/TestCase/IndexTest.php
- tests/TestCase/MarshallerTest.php
- tests/TestCase/ResultSetTest.php
- Implement get/set for schema and entityClass
- Update docs references for table to index
> Update more deprecated methods from Table to Index class

- src/Index.php
- tests/TestCase/IndexTest.php
This adds support for saving documents with routing keys.
> Add support for saving documents using routing keys

- composer.json
> Stick elastica only in 6.x

- .github/workflows/ci.yml
Use latest image and port some build script cleanup.
> Test with elasticsearch 7.11.1

- src/IndexRegistry.php
- tests/TestCase/IndexRegistryTest.php
Code was ported from `TableLocator`
> Add IndexRegistry::$fallbackClassName

- src/Query.php
- tests/TestCase/QueryTest.php
https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html
> Add collapse search results option
