src/Document.php, src/Marshaller.php, src/Type.php, tests/TestCase/MarshallerTest.php, tests/TestCase/TypeTest.php
Add basic single entity patching methods to the marshaller. I've also fixed a few small issues around hydrated objects not having their `id` property set.
=> Marshal update

src/Association/EmbedMany.php, src/Association/EmbedOne.php, src/Association/Embedded.php, src/Document.php, src/ResultSet.php, src/Type.php, tests/Fixture/ProfilesFixture.php, tests/TestCase/DocumentTest.php, tests/TestCase/EmbeddedDocumentTest.php, tests/TestCase/ResultSetTest.php
This adds the concept of embedded documents when reading data out of elastic search. I've intentionally not tried to address writes right now and will do that in a following pull request.
Embedded documents allow you to embed different entity classes to sections of a complex document, giving you more flexibility around how you model data in elasticsearch.
*  Are the names for the methods/classes reasonable and sensical?
* Should we be trying to share any code with the relational ORM?
=> Add embedded documents when reading

src/Association/EmbedMany.php, src/Association/EmbedOne.php, src/Association/Embedded.php, src/Marshaller.php, tests/TestCase/MarshallerTest.php, tests/TestCase/TypeTest.php
This adds the ability to marshal and save embedded documents. The features are still pretty minimal, but functional. To come in future pull requests:
* Validation for embedded documents.
* Deeply nested embedded documents.
These will likely both end up as dot separated paths, but I've not yet considered what happens in the scenario where there are deeply nested paths with missing branch elements, or how deeply nested structures expand out.
=> Marshal and save embedded documents

composer.json, src/Type.php, src/TypeRegistry.php, tests/TestCase/TypeRegistryTest.php, tests/init.php, tests/testapp/Plugin/TestPlugin/src/Model/Type/CommentsType.php
This adds a static factory for Type mappers that behaves very similar to the one used with the ORM. My reasoning around this was:
* It provides a simple hook for `ModelAwareTrait` to use.
* It makes getting type instances much simpler as the end developer doesn't need to manage connections as much.
After this, I'll look into some bootstrapping code that will help automatically wire the plugin into controllers/shells, and wire up the FormHelper context.
=> Implement the TypeRegistry

src/Datasource/Connection.php, src/Datasource/MappingSchema.php, src/Datasource/SchemaCollection.php, src/Document.php, src/FilterBuilder.php, src/Marshaller.php, src/Query.php, src/ResultSet.php, src/TestSuite/TestFixture.php, src/Type.php, src/View/Form/DocumentContext.php, tests/TestCase/Datasource/ConnectionTest.php, tests/TestCase/DocumentTest.php, tests/TestCase/FilterBuilderTest.php, tests/TestCase/MarshallerTest.php, tests/TestCase/QueryTest.php, tests/TestCase/TypeTest.php, tests/init.php
Follows https://github.com/cakephp/elastic-search/pull/39
A couple param/return descriptions are a little generic. Feel free to elaborate.
The remaining errors are protected methods lacking an underscore prefix and the FilterBuilder `and_()` & `or_()` methods not being camel cased. Should we just adjust the protected methods to follow suit for the time being, and update when/if drop that convention as a whole?
=> Fix CS errors and a couple typos

composer.json
to allow the plugin to be automatically listed in `vendor/cakephp-plugins.php`.
Also add basics keyword and information on bug tracker and authors based on migrations plugin.
=> add cakehp-plugin type to composer.json

.travis.yml, README.md, src/Datasource/Connection.php, src/Datasource/SchemaCollection.php, src/TestSuite/TestFixture.php, src/Type.php, tests/Fixture/ArticlesFixture.php, tests/Fixture/ProfilesFixture.php
Do a bunch of updates related to new features in 3.1
* Use the new interfaces to avoid hinting on specific implementations.
* Remove useless methods in Connection now that there is a small formal interface.
* Actually implement `listTables()`. While a bad name, we don't have a good interface with a more reasonable name.
=> 3.1 Updates

src/Document.php, src/ResultSet.php, tests/TestCase/DocumentTest.php, tests/TestCase/ResultSetTest.php
Having a hold of the `Elastica\Result` inside Documents is pretty important. Without this, it is not possible to access information such as the document score, highlights or the type it came from.
=> Make sure the Elastica\Result is remembered in Documents

src/FilterBuilder.php
Bit of a nitpick, but with __call handling the and/or calls, I think these can be tucked away as protected -- rather than having multiple names to the same end.
=> Make and/or methods protected

src/FilterBuilder.php
Fixes CS build. Ignore the naming convention standard for these 2 methods. (for now?) Perhaps only until when/if new method names are used.
=> Ignore CS for and_ and or_ method names

src/TestSuite/TestFixture.php
This methods are called by the FixtureManager in order to add / drop foreign key constraints to the tables.
Since Elasticsearch does not use the concept of foreign key constraints, these methods are no-op
To be merged when /if the refs PR https://github.com/cakephp/cakephp/pull/7503 is merged
=> Add the two new methods dealing with foreign key constraints

src/Datasource/Connection.php, src/TestSuite/TestFixture.php
Now that interfaces were extracted for ``Connection`` and ``Fixtures`` objects, the ElasticSearch ``Connection`` and ``Fixtures`` objects should implements them.
=> Make the Connection and Fixtures objects implements the needed interfaces

src/Query.php, tests/TestCase/QueryTest.php
Will allow for code like this
````php
$result = TypeRegistry::get('ElasticLocation')
->find('city')
->find('forRequest')
->find('within', compact('latitude', 'longitude'))
->first();
````
=> Allow find() call chaining like DB ORM

src/Type.php, tests/TestCase/TypeTest.php
This lets the elasticsearch plugin work more like the ORM.
Refs #84
=> Add default conventional event mappings.

README.md, src/Datasource/Connection.php, tests/TestCase/Datasource/ConnectionTest.php
Default to the `Elastica\Log` object if no logging profile is defined. This makes our wrappers do what `Elastica` would naturally do when configured in a naive way.
Refs #94
=> Fix missing logger instance.

src/Query.php, tests/TestCase/QueryTest.php
This simplifies the way we store the main wrapper BoolQuery, and sets the foundation for supporting should and must_not clauses.
Open Questions:
* What is a good naming for adding `should` and `must_not` clauses?
* Is `search()` actually a good name?
* How do we communicate to newcomers the differences between `where()` and `search()` and the methods are are to come?
=> Working towards supporting should and must_not clauses

config/bootstrap.php, tests/TestCase/QueryTest.php, tests/TestCase/ResultSetTest.php, tests/TestCase/TypeTest.php
Use Dispatcher.invokeController as it works more consistently between various versions of CakePHP. In 3.3+ `Dispatcher.beforeDispatch` doesn't always have access to the Controller depending on how the application is setup.
Refs #109
=> Fix event usage.

src/Type.php, tests/TestCase/TypeTest.php
Type objects should be bound to their own event manager.
=> Listen for events

src/Index.php, src/Marshaller.php, src/ResultSet.php, src/TestSuite/TestFixture.php, src/View/Form/DocumentContext.php, tests/TestCase/EmbeddedDocumentTest.php, tests/TestCase/IndexRegistryTest.php, tests/TestCase/IndexTest.php, tests/TestCase/MarshallerTest.php, tests/TestCase/QueryTest.php, tests/TestCase/View/Form/DocumentContextTest.php
Reviewing the latest changes, I found some flaws.
Plus the fixes, I updated how mapping type is derived from Index name, when not explicitly defined.
I think that way should be more clear the differences between 'Index' and (mapping) 'Type' names.
=> Fix use of deprecated methods

src/QueryBuilder.php
Hi guys,
I noticed that the match function is missing in QueryBuilder. Is it missing for a special reason?
Thanks.
=> add match function to the QueryBuilder

.travis.yml, src/Index.php, src/Rule/IsUnique.php, tests/TestCase/IndexTest.php, tests/TestCase/QueryBuilderTest.php, tests/TestCase/RulesCheckerTest.php
- Added an IsUnique rule
- Add 'refresh' option on save/delete operations
- Fix tests for [Elastica 6.0.2](https://github.com/ruflin/Elastica/blob/master/CHANGELOG.md) - Use ``source`` script field instead of deprecated (since ES 5.6) ``inline``
- Update ElasticSearch version in tests to 6.2.4
=> Add IsUique rule, Add 'refresh'

src/ResultSet.php, tests/TestCase/ResultSetTest.php
This PR makes sure that ResultSet uses Cake\Datasource\ResultSetInterface including the added 'bonus' of the serializable interface requirement.
=> Make ResultSet use ResultSetInterface

composer.json, src/View/Form/DocumentContext.php, tests/TestCase/View/Form/DocumentContextTest.php
This PR makes DocumentContext work correctly when using validation errors coming from a nested Validator setup. Also changed Document requirement to EntityInterface
=> Add support for nested validator errors

src/View/Form/DocumentContext.php, tests/TestCase/View/Form/DocumentContextTest.php
Tests will fail because of an issue in Cake core that needs to be resolved first so **do not merge** this one just yet. 
Refs https://github.com/cakephp/cakephp/pull/12250
=> Support nested validation errors on nonexistent entities

src/QueryBuilder.php, tests/TestCase/QueryBuilderTest.php
Queries with numerically indexed conditions currently fail in 3.0 due to strict typing (see attached test).
```
TypeError: strtolower() expects parameter 1 to be string, int given
/www-root/vendor/cakephp/elastic-search/src/QueryBuilder.php:683
```
This breaks use cases where we want to directly use QueryExpression classes without operators and prevents us from upgrading to Cake 4. Simply moving the `strtolower` to after handling the numeric case fixes the issue.
=> Fix QueryBuilder with numerically indexed arrays

src/Association/EmbedMany.php, src/Association/EmbedOne.php, src/Association/Embedded.php, src/Document.php, src/Exception/MissingDocumentException.php, src/Index.php, src/Marshaller.php, src/ResultSet.php, tests/TestCase/EmbeddedDocumentTest.php, tests/TestCase/IndexTest.php, tests/init.php
Same changes as I did on 2.x branch.
=> Split get/set from embedded

composer.json, src/Marshaller.php
Prevent installing Elasticsearch 3 with CakePHP 3.
Fixes #248.
=> Add Composer constraint for CakePHP

composer.json
Add cakephp requirement to composer the same as https://github.com/cakephp/elastic-search/pull/250.
If we don't add it to 2.x, then that doesn't prevent the original issue.
=> 2.x - Add cakephp requirement

.github/workflows/ci.yml, README.md, composer.json, docs/en/index.rst, src/Datasource/MappingSchema.php, src/Document.php, src/Index.php, src/Query.php, src/QueryBuilder.php, src/TestSuite/TestFixture.php, tests/Fixture/ArticlesFixture.php, tests/TestCase/DocumentTest.php, tests/TestCase/IndexTest.php, tests/TestCase/QueryBuilderTest.php, tests/TestCase/QueryTest.php, tests/TestCase/ResultSetTest.php, tests/testapp/TestApp/src/Model/Index/AccountsIndex.php, tests/testapp/TestApp/src/Model/Index/UsersIndex.php
Note: this is an early draft to get all the tests passing. I did not yet have a chance to test this in our application, or check for correctness of the changes. I'm submitting here for visibility and to get some early feedback.
Notable changes:
- Mapping types are removed in Elastica 7, so I replaced them with the equivalent Index methods everywhere
- I've enabled tests for PHP 8.0 and fixed the missing return type. I think the return type may be backported to 3.x to ease upgrading
- Breaking: I removed `Document::getType()` since it is no longer applicable
- Breaking: `QueryBuilder::geoShapeIndex()` has changed arguments
- The tests for routing keys need an index with the correct number of routing shards in ES 7. I needed to extend the TestFixture for this.
- …
=> Upgrade to Elastica 7 and enable tests for PHP 8.0
